---
variables:
  LEKTOR_BUILD_FLAGS: scss
  SITE_URL: www.torproject.org
  STAGING_URL: www.staging.torproject.net
  TRANSLATION_BRANCH: tpo-web
  LEKTOR_PARTIAL_BUILD: 1

include:
  - project: kez/ci-templates
    file:
      - lektor.yml
      - static-shim-deploy.yml

# for review apps (branches), move some press content out of the way to decrease
# the build time by a factor of at least 4x -- keep only the last 1 year of
# press articles
.setup-lektor-partial-build:
  - export CUTOFF=$(date -d "$(date +%Y-%m-%d) -365 day" +%Y-%m-%d)
  - awk '{if($1=="pub_date:" && $2 < ENVIRON["CUTOFF"])print FILENAME}' content/press/*/contents.lr | while read -d $'\n' f; do rm "$f"; done
